config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'

  get 'admin', to: 'pages#admin'
  get 'mentions_legales', to: 'pages#mentions_legales'

  resources :products
    get 'products/:id/research', to: "products#research", as: "product_research"
  resources :orders do
    resources :payments, only: :new
  end

  resources :order_gifts do
    resources :payment_gifts, only: :new
  end

  resources :line_items
    post 'line_items/:id/add', to: "line_items#add_quantity", as: "line_item_add"
    post 'line_items/:id/reduce', to: "line_items#reduce_quantity", as: "line_item_reduce"
  resources :carts
  post 'without_login', to: 'orders#without_login'
  post 'without_login', to: 'order_gifts#without_login'
  # resources :contacts, only: [:new, :create]
  resources :promotions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_bandeau.html.erb
<div class="bandeau">
  <p>Frais de livraison 3,90€ (France),</p>
  <p>livraison offerte à partir de 60€ d'achats</p>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <%= image_tag "logo-footer.png" %>
  <div class="footer-center">
    <a href="https://grainedemomes.com/3-le-dressing">LOCATION</a>
    <a href="https://grainedemomes.com/content/14-la-mission" target="blank">NOTRE MISSION</a>
    <a href="https://grainedemomes.com/content/4-vos-questions" target="blank">VOS QUESTIONS</a>
    <a href="https://grainedemomes.com/content/15-les-marques" target="blank">LES MARQUES</a>
    <%= link_to "MENTIONS LEGALES", mentions_legales_path %>
   <!--  <a href="https://grainedemomes-shop.com/mentions_legales" target="blank">MENTIONS LEGALES</a> -->
    <a href="https://grainedemomes.com/content/3-graine-de-momes-cgv" target="blank">CGV</a>
  </div>
  <div>
    <a href="https://www.instagram.com/grainedemomes/" target="blank"><img src="../assets/insta.png" alt="" style="height: 30px; width: 30px;"></a>
    <a href="https://www.facebook.com/grainedemome/"><img src="../assets/icone-facebook.png" alt="" style="height: 30px; width: 30px;"></a>
  </div>
</div>

<!--   <a href="#" style="font-size: 12px">Made by EMMROSE</a> -->

app/views/shared/_margin-navbar.html.erb
<div class="margin-navbar">

</div>

app/views/shared/_navbar.html.erb
<div class="navbar-lewagon">
  <div class="nav-items">
    <a href="https://grainedemomes.com/"><img src="../assets/logo.png" alt=""></a>
    <%= link_to "OFFRIR", new_order_gift_path %>
    <a href="https://grainedemomes.com/content/13-la-location-mode-d-emploi">LOUER</a>
    <a href="https://grainedemomes.com/content/1-guide-des-tailles" target="blank">GUIDE DES TAILLES</a>
  </div>


  <div class="cart">
    <%= link_to cart_path(@current_cart) do %>
      <i class="fab fa-opencart"></i>
      <% cart = @current_cart %>
      <% items = 0 %>
      <% cart.line_items.each do |i| %>
        <% items += 1 %>
      <% end %>
      <% if items > 0 %>
        <p><%= items %></p>
      <% end %>
    <% end %>
  </div>
</div>
<% if params[:controller] == "pages"%>
  <%= render 'shared/search_filters' %>
<% end %>

app/views/shared/_picto.html.erb
<div class="pictos">
  <div class="picto">
    <img src="../assets/picto1.png" alt="">
    <p>Paiement sécurisé</p>
  </div>
  <div class="picto">
    <img src="../assets/picto2.png" alt="">
    <p>Livraison en France métropolitaine</p>
  </div>
  <div class="picto">
    <img src="../assets/picto3.png" alt="">
    <p>Service Client</p>
  </div>
</div>

app/views/shared/_search_filters.html.erb
<div class="hide-desktop filters-mobile-dropdown" style="">
  <a class="flex-grow-1" data-toggle="collapse" href="#collapseFilters" role="button" aria-expanded="false" aria-controls="collapseFilters">
    Filtres
  </a>
  <%= link_to root_path, class: "clear-filters" do %>
    Effacer les filtres
  <% end %>
</div>
<div class="collapse" id="collapseFilters">
    <div class="container-filters bg-white">
      <!-- select one (or several) categories tag among all activities available at this location-->
      <div class="filters">

        <% if params[:category] %>
          <%= link_to root_path(request.query_parameters.except(:category)), class: "btn filter filter-selected" do %>
            <%= @products.find_by(category: params[:category]).category.name %> <i class="fas fa-times"></i>
          <% end %>
        <% else %>
          <div class="filter activity-filters dropdown">
            <button class="btn filter-btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Catégorie
            </button>
            <div class="dropdown-menu animated fadeIn" aria-labelledby="dropdownMenuButton">
              <% categories = [] %>
              <% @products.each do |product| %>
                <% categories << product.category %>
              <% end %>
              <% categories.uniq.each do |category| %>
                <% request.query_parameters[:category] = category %>
                <%= link_to root_path(request.query_parameters), class: "dropdown-item" do %>
                  <%= category.name %>
                <% end %>
                <% request.query_parameters.except!(:category) %>
              <% end %>
            </div>
          </div>
        <% end %>
        <!-- FILTER BY GENRE -->
        <% if params[:genre] %>
          <%= link_to root_path(request.query_parameters.except(:genre)), class: "btn filter filter-selected" do %>
            <%= @products.find_by(genre: params[:genre]).genre.name %> <i class="fas fa-times"></i>
          <% end %>
        <% else %>
          <div class="filter activity-filters dropdown">
            <button class="btn filter-btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Genre
            </button>
            <div class="dropdown-menu animated fadeIn" aria-labelledby="dropdownMenuButton">
              <% genres = [] %>
              <% @products.each do |product| %>
                <% genres << product.genre %>
              <% end %>
              <% genres.uniq.each do |genre| %>
                <% request.query_parameters[:genre] = genre %>
                <%= link_to root_path(request.query_parameters), class: "dropdown-item" do %>
                  <%= genre.name %>
                <% end %>
                <% request.query_parameters.except!(:genre) %>
              <% end %>
            </div>
          </div>
        <% end %>
        <!-- FILTER BY SIZE -->
        <% if params[:size] %>
          <%= link_to root_path(request.query_parameters.except(:size)), class: "btn filter filter-selected" do %>
            <%= @products.find_by(size: params[:size]).size.name %> mois <i class="fas fa-times"></i>
          <% end %>
        <% else %>
          <div class="filter activity-filters dropdown">
            <button class="btn filter-btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Taille
            </button>
            <div class="dropdown-menu animated fadeIn" aria-labelledby="dropdownMenuButton">
              <% sizes = [] %>
              <% @products.each do |product| %>
                <% sizes << product.size %>
              <% end %>
              <% sizes.uniq.each do |size| %>
                <% request.query_parameters[:size] = size %>
                <%= link_to root_path(request.query_parameters), class: "dropdown-item" do %>
                  <%= size.name %> mois
                <% end %>
                <% request.query_parameters.except!(:size) %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>

      <%= link_to root_path, class: "clear-filters hide-tablet" do %>
        Supprimer les filtres
      <% end %>

    </div>
</div>