config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'

  get 'admin', to: 'pages#admin'
  get 'mentions_legales', to: 'pages#mentions_legales'

  resources :products
    get 'products/:id/research', to: "products#research", as: "product_research"
  resources :orders do
    resources :payments, only: :new
  end

  resources :order_gifts do
    resources :payment_gifts, only: :new
  end

  resources :line_items
    post 'line_items/:id/add', to: "line_items#add_quantity", as: "line_item_add"
    post 'line_items/:id/reduce', to: "line_items#reduce_quantity", as: "line_item_reduce"
  resources :carts
  post 'without_login', to: 'orders#without_login'
  post 'without_login', to: 'order_gifts#without_login'
  # resources :contacts, only: [:new, :create]
  resources :promotions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/admin.html.erb
<div class="container" style="margin-top: 100px;">
  <%= link_to "Log out", destroy_user_session_path,class: "btn btn-primary", method: :delete %>
  <h1>Les produits</h1>
  <div>
    <a href="<%=new_product_path%>" class="btn btn-primary">Nouveau Produit</a>
    <br>
  <p>Rechercher un produit :</p>
      <div class="search mt-2">
        <%= form_tag products_path, method: :get, novalidate: "novalidate", class: "simple_form search"  do %>
          <div class="search-form-control form-group mt-1 mb-0">
            <%= text_field_tag :query,
                params[:query],
                class: "search-input form-control string required",
                id: "search_query",
                placeholder: "Effectuer une recherche par nom ou par n° de référence",
                value: ""
            %>
            <%= button_tag(type: "submit", class: "btn btn-flat") do %>
              <i class="fas fa-search"></i> Search
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <h1>Les Promotions en cours</h1>
    <div>
      <% if Promotion.count > 0 %>
        <% @promotions = Promotion.all %>
        <% @promotions.each do |promotion| %>
          <p>code promo: <%= promotion.code %> // réduction de <%= promotion.reduction %></p>
          <%= link_to promotion_path(promotion), method: :delete, class: "py-2 px-4 ml-2 bd-highlight bg-light rounded",data: { confirm: "Etes vous sûre ?" } do %>
            <i class="fas fa-trash"></i>
          <% end %>
        <% end %>
      <% else %>
        <p>Aucune promotion actuellement</p>
      <% end %>
    </div>
    <br>
    <a href="<%=new_promotion_path%>" class="btn btn-primary">Nouveau code promo</a>
  </div>

</div>

app/views/pages/home.html.erb
<div>
  <div class="home">
    <h2>Vide-dressing</h2>
    <h5>Jusqu'à -70% du prix neuf</h5>
    <img src="../assets/coeur-background.png" alt="">
    <p>Vous craquez sur un modèle mais la taille n'est pas disponible ? Envoyez nous un mail à bonjour@grainedemomes.com</p>
  </div>
  <div class="cards">
    <% @products.each do |product| %>
      <% if product.stock > 0 %>
        <div class="wrapper">
          <div class="top">
            <%= link_to product_path(product) do %>
              <span><%= cl_image_tag product.cover.key, class: "front-picture"%></span>
              <span><%= cl_image_tag product.photo.key, class: "back-picture"%></span>
              <span class="size"><%= product.size.name %> mois</span>
            <% end %>
          </div>
          <div class="bottom">
            <div style="display:flex;">
              <h3><%= product.name %></h3>
              <%= link_to line_items_path(product_id: product.id), method: :post, remote: true do %>
                <i class="fas fa-cart-plus" id="icone"></i>
              <% end %>
            </div>
            <div style="display:flex;">
              <h5><%= product.price %>€</h5>
              <!-- icone eye for smallest device -->
              <%= link_to product_path(product) do %>
                <i class="fas fa-eye" id="eye"></i>
              <% end %>
              <h5 id="savoir"><%= link_to "en savoir +", product_path(product) %></h5>
            </div>
          </div>
        </div>
      <% else %>
        <div class="wrapper">
          <div class="top">
            <%= link_to product_path(product) do %>
              <span><%= cl_image_tag product.cover.key, class: "front-picture"%></span>
              <span><%= cl_image_tag product.photo.key, class: "back-picture"%></span>
              <span class="size"><%= product.size.name %> mois</span>
            <% end %>
          </div>
          <div class="bottom">
            <div style="display:flex;">
              <h3><%= product.name %></h3>
              <!-- If quantity equal 0, Product cannot be added to a cart -->
              <p id="available">Victime de son succès</p>
            </div>
            <div style="display:flex;">
              <h5><%= product.price %>€</h5>
              <!-- icone eye for smallest device -->
              <%= link_to product_path(product) do %>
                <i class="fas fa-eye" id="eye"></i>
              <% end %>
              <h5 id="savoir"><%= link_to "en savoir +", product_path(product) %></h5>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>