config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'

  get 'admin', to: 'pages#admin'
  get 'mentions_legales', to: 'pages#mentions_legales'

  resources :products
    get 'products/:id/research', to: "products#research", as: "product_research"
  resources :orders do
    resources :payments, only: :new
  end

  resources :order_gifts do
    resources :payment_gifts, only: :new
  end

  resources :line_items
    post 'line_items/:id/add', to: "line_items#add_quantity", as: "line_item_add"
    post 'line_items/:id/reduce', to: "line_items#reduce_quantity", as: "line_item_reduce"
  resources :carts
  post 'without_login', to: 'orders#without_login'
  post 'without_login', to: 'order_gifts#without_login'
  # resources :contacts, only: [:new, :create]
  resources :promotions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items
  belongs_to :user, optional: true

  def sub_total
    sum = 0
    self.line_items.each do |line_item|
      sum+= line_item.total_price
    end
    return sum
  end

  def promotion
    sub_total >= 60.to_money ? " offert" : " 3,90 €"
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authenticate_user!

  def show
    @cart = @current_cart
    @line_items = @cart.line_items.order(:created_at)
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end
end

app/views/carts/show.html.erb
<div class="container">
  <% if @line_items.empty? %>
      <%= link_to products_path do %>
        <button>Retour à la Boutique</button>
      <% end %>
  <% else %>
    <div>
      <h2><%= "Mon panier"%></h2><br>
      <div class="cart-items">
        <% @line_items.each do |line_item| %>
          <div class="cart-item">
            <div class="cart-item-left">
              <%= cl_image_tag line_item.product.cover.key%>
                <%= line_item.product.name %> <br>
                <%= line_item.product.size.name %> mois
            </div>
            <div class="cart-item-right">
              <p><%= line_item.product.price %> €</p>
              <%= link_to line_item_path(line_item), method: :delete do%>
                <i class="fas fa-trash"></i>
              <% end %>
            </div>
          </div>
          <br>
        <% end %>
      </div>
      <div class="total-amount">
        <div style="display:flex; align-items: center;">
          <h4>Total de ma commande: &nbsp;</h4>
          <h4>  <%= (@cart.sub_total) %> €</h4>
        </div>
        <div style="display:flex; align-items: center;">
          <h6>Frais de port: &nbsp;</h6>
          <h6><%= (@cart.promotion) %></h6>
        </div>
          <%= link_to new_order_path do %>
            <button class="btn-oval">Commander</button>
          <% end %>
      </div>
      <br>
      <div style="display:flex; flex-direction: row;">
        <%= link_to cart_path, method: :delete, data: {confirm: 'are_you_sure?'} do %>
          <i class="fas fa-trash" style="color: #e13a40;"> </i>
        <% end %>
        <p style="color: #e13a40;">Videz mon panier</p>
      </div>
  <% end %>
</div>