config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'

  get 'admin', to: 'pages#admin'
  get 'mentions_legales', to: 'pages#mentions_legales'

  resources :products
    get 'products/:id/research', to: "products#research", as: "product_research"
  resources :orders do
    resources :payments, only: :new
  end

  resources :order_gifts do
    resources :payment_gifts, only: :new
  end

  resources :line_items
    post 'line_items/:id/add', to: "line_items#add_quantity", as: "line_item_add"
    post 'line_items/:id/reduce', to: "line_items#reduce_quantity", as: "line_item_reduce"
  resources :carts
  post 'without_login', to: 'orders#without_login'
  post 'without_login', to: 'order_gifts#without_login'
  # resources :contacts, only: [:new, :create]
  resources :promotions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :genre
  belongs_to :size
  has_many :line_items, dependent: :destroy

  validates :name, presence: true #, length: { in: 3...16 }
  validates :description, presence: true, length: { in: 6...150 }
  validates :price_cents, presence: true, numericality: { greater_than: 0 }
  validates :old_price_cents, presence: true, numericality: { greater_than: 0 }
  validates :sku, presence: true, uniqueness: true

  monetize :price_cents
  monetize :old_price_cents

  has_one_attached :photo
  has_one_attached :cover

  #pg search
  include PgSearch::Model
  pg_search_scope :search_by_name_sku,
    against: [ :name, :sku ],
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]

    def index
      # Category filter
      @products = @products.where(category: params[:category]) if params[:category].present?
      # Genre filter
      @products = @products.where(genre: params[:genre]) if params[:genre].present?
      # # Size filter
      @products = @products.article.where(size: params[:size]) if params[:size].present?

      @products = Product.all
    end

    def research
      if params[:query].present?
        @products = Product.search_by_name_sku(params[:query])
      else @products = Product.all
      end
      if @products.count == 0
        @products = Product.all
      end
    end

    def show
      @product = Product.find(params[:id])
    end

    def new
      @product = Product.new
    end

    def create
      @product = Product.new(product_params)
      if @product.save
        redirect_to root_path
        flash[:notice] = "Votre produit a bien été enregistré."
      else
        render :new
        flash[:alert] = "Veuillez compléter le formulaire s'il vous plaît."
      end
    end

    def edit
      @product = Product.find(params[:id])
    end

    def update
      @product = Product.find(params[:id])
      if @product.update(product_params)
        redirect_to product_path(@product)
      else render :edit
      end
    end

    def destroy
      @product = Product.find(params[:id])
      @product.destroy
      redirect_to products_path
    end

    private

    def product_params
      params.require(:product).permit(:name, :description, :size_id, :genre_id, :category_id, :sku, :cover, :photo, :price_cents, :old_price_cents, :stock)
    end
    # Ne pas oublier de remettre photos: []
end

app/views/products/edit.html.erb
<div class="container form-container">
 <%= simple_form_for(@product) do |f| %>
   <div class="form-top">
    <div class="gift-choices">
      <fieldset class="form-group required">
        <input type="hidden" name="product[category_id][]" value="">
        Choose your category?

        <div>
          <% Category.all.each do |category| %>
            <input class="d-none required" type="radio" value="<%= category.id %>" name="product[category_id]" id="product_category_id_<%= category.id %>">
            <label class="form-check-label-gift collection_radio_buttons gift-choice" for="product_category_id_<%= category.id %>">
              <%= category.name %>
            </label>
          <% end %>
        </div>
      </fieldset>
    </div>
    <div class="gift-choices">
      <fieldset class="form-group required">
        <input type="hidden" name="product[size_id][]" value="">
        Choose your size?

        <div>
          <% Size.all.each do |size| %>
            <input class="d-none required" type="radio" value="<%= size.id %>" name="product[size_id]" id="product_size_id_<%= size.id %>">
            <label class="form-check-label-gift collection_radio_buttons gift-choice" for="product_size_id_<%= size.id %>">
              <%= size.name %>
            </label>
          <% end %>
        </div>
      </fieldset>
    </div>
    <div class="gift-choices">
      <fieldset class="form-group required">
      <input type="hidden" name="product[genre_id][]" value="">
      Choose your genre?

      <div>
        <% Genre.all.each do |genre| %>
          <input class="d-none required" type="radio" value="<%= genre.id %>" name="product[genre_id]" id="product_genre_id_<%= genre.id %>">
          <label class="form-check-label-gift collection_radio_buttons gift-choice" for="product_genre_id_<%= genre.id %>">
            <%= genre.name %>
          </label>
        <% end %>
      </div>
      </fieldset>
    </div>

    <%= f.input :name, label: 'Nom' %>
    <p>Prix en boutique</p>
    <%= f.number_field :old_price_cents, label: "Prix (en centimes)" %>
    <br>
    <p>Prix Graîne de mômes</p>
    <%= f.number_field :price_cents, label: "Prix (en centimes)"%>
    <p>Quantité disponible</p>
    <%= f.number_field :stock %>
    <%= f.input :sku, label: 'Référence (SKU)' %>
    <%= f.input :description, label: 'Ajoutez une description', as: :text %>
    <div class="d-flex">
      <%= f.input :cover, label: 'Ajoutez une photo de couverture', as: :file %>
      <%= f.input :photo, label: 'Ajoutez une seconde photo', as: :file %>
    </div>
   </div>
   <div class="form-button">
    <%= f.submit "Créer le produit", class: 'btn btn-primary' %>
   </div>
   <br>
 <% end %>
</div>

app/views/products/index.html.erb
<div class="container">
  <div class="cards" style="margin-top: 100px;">
    <% @products.each do |product| %>
      <div class="wrapper">
        <div class="top">
          <%= link_to product_path(product) do %>
            <span><%= cl_image_tag product.cover.key, class: "front-picture"%></span>
            <span class="size"><%= product.size.name %> mois</span>
          <% end %>
        </div>
        <div class="bottom">
          <div style="display:flex;">
            <h3><%= product.name %></h3>
            <%= link_to line_items_path(product_id: product.id), method: :post do %>
              <i class="fas fa-cart-plus" id="icone"></i>
            <% end %>
          </div>
          <div style="display:flex;">
            <h5> <%= product.price %>€</h5>
            <h5><%= link_to "en savoir +", product_path(product) %></h5>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<div class="container form-container">
 <% new_product = Product.new %>
 <%= simple_form_for(new_product) do |f| %>
   <div class="form-top">
    <div class="gift-choices">
      <fieldset class="form-group required">
        <input type="hidden" name="product[category_id][]" value="">
        Choose your category?

        <div>
          <% Category.all.each do |category| %>
            <input class="d-none required" type="radio" value="<%= category.id %>" name="product[category_id]" id="product_category_id_<%= category.id %>">
            <label class="form-check-label-gift collection_radio_buttons gift-choice" for="product_category_id_<%= category.id %>">
              <%= category.name %>
            </label>
          <% end %>
        </div>
      </fieldset>
    </div>
    <div class="gift-choices">
      <fieldset class="form-group required">
        <input type="hidden" name="product[size_id][]" value="">
        Choose your size?

        <div>
          <% Size.all.each do |size| %>
            <input class="d-none required" type="radio" value="<%= size.id %>" name="product[size_id]" id="product_size_id_<%= size.id %>">
            <label class="form-check-label-gift collection_radio_buttons gift-choice" for="product_size_id_<%= size.id %>">
              <%= size.name %>
            </label>
          <% end %>
        </div>
      </fieldset>
    </div>
    <div class="gift-choices">
      <fieldset class="form-group required">
      <input type="hidden" name="product[genre_id][]" value="">
      Choose your genre?

      <div>
        <% Genre.all.each do |genre| %>
          <input class="d-none required" type="radio" value="<%= genre.id %>" name="product[genre_id]" id="product_genre_id_<%= genre.id %>">
          <label class="form-check-label-gift collection_radio_buttons gift-choice" for="product_genre_id_<%= genre.id %>">
            <%= genre.name %>
          </label>
        <% end %>
      </div>
      </fieldset>
    </div>
    <%= f.input :name, label: 'Nom', placeholder: "Nom du produit" %>
    <p>Prix boutique</p>
    <%= f.number_field :old_price_cents, label: "Prix (en centimes)", placeholder: 0%>
    <br>
    <p>Prix Graine de mômes</p>
    <%= f.number_field :price_cents, label: "Prix (en centimes)", placeholder: 0%>
    <p>Quantité disponible</p>
    <%= f.number_field :stock %>
    <%= f.input :sku, label: 'Référence (SKU)', placeholder: "Référence du produit" %>
    <%= f.input :description, label: 'Ajoutez une description', as: :text, placeholder: "Rédiger ici la description du produit..." %>
    <div class="d-flex">
      <%= f.input :cover, label: 'Ajoutez une photo de couverture', as: :file %>
      <%= f.input :photo, label: 'Ajoutez une seconde photo', as: :file %>
    </div>
   </div>
   <div class="form-button">
    <%= f.submit "Créer le produit", class: 'btn btn-primary' %>
   </div>
   <br>
 <% end %>
</div>

app/views/products/show.html.erb
<div class= "container">
  <div class= "product">
    <div class= "product-illustration">
      <%= cl_image_tag @product.cover.key %>
      <%= cl_image_tag @product.photo.key %>
    </div>
    <div class= "product-description">
      <div class= "description">
        <h1><strong><%= @product.name %></strong></h1>
        <h5><%= @product.description %></h5>
        <h5>Taille: <%= @product.size.name %> mois</h5>
        <h5>Prix neuf: <%= @product.old_price%> €</h5>
        <h4>Prix Graine de Mômes: <%= @product.price%>€</h4>
      </div>
      <div class= "price">
        <% if @product.stock > 0 %>
          <%= link_to "Achetez", line_items_path(product_id: @product.id), method: :post, class: "btn-oval", id: "btn-product" %>
        <% end %>
        <div class= "link">
          <%= link_to root_path do %>
            Retour à la Boutique
          <% end %>
        </div>
      </div>
      <div>
        <% if user_signed_in? %>
          <br>
          <ul>
            <%= link_to edit_product_path(@product), class: "py-2 px-4 ml-2 bd-highlight bg-light rounded" do %>
              <i class="fas fa-pencil-alt"></i> Edit
            <% end %>
            <%= link_to product_path(@product), method: :delete, class: "py-2 px-4 ml-2 bd-highlight bg-light rounded",data: { confirm: "Etes vous sûre ?" } do %>
              <i class="fas fa-trash"></i>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
</div>